name: troli_gsc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.0.0
  time_remaining: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/image/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
